(()=>{'use strict';
let data,token,panel='overview',dirty=false,uploadTarget=null;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={overview:'نظرة عامة',brand:'الهوية والتواصل',motion:'الموشن والمشاهد',partners:'الشركاء والشعارات',copy:'محتوى الموقع'};
function get(path){return path.split('.').reduce((a,k)=>a?.[k],data)}function put(path,value){const keys=path.split('.'),last=keys.pop();let o=data;for(const k of keys){if(['__proto__','constructor','prototype'].includes(k))return;o=o[k]}o[last]=value;setDirty()}
function setDirty(){dirty=true;$('#dirty-label').textContent='تعديلات غير محفوظة';}
function status(text,error=false){$('#status').textContent=text;$('#status').classList.toggle('error',error)}
async function api(url,body){const r=await fetch('/api/'+url,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-Admin-Token':token},body:body===undefined?undefined:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error||'تعذر تنفيذ الطلب');return j;}
function field(label,path,type='text',options){const v=get(path);if(type==='checkbox')return `<label class="toggle"><input type="checkbox" data-path="${path}" ${v?'checked':''}>${label}</label>`;if(type==='select')return `<label class="form-field"><span>${label}</span><select data-path="${path}">${options.map(([id,name])=>`<option value="${id}" ${v===id?'selected':''}>${name}</option>`).join('')}</select></label>`;return `<label class="form-field"><span>${label}</span>${type==='textarea'?`<textarea data-path="${path}" dir="auto">${esc(v)}</textarea>`:`<input type="${type}" data-path="${path}" value="${esc(v)}" ${type==='number'?'step="0.1"':''} dir="auto">`}</label>`}
function imageField(label,path){return `<div class="form-field"><span>${label}</span><div class="upload-row"><input data-path="${path}" value="${esc(get(path))}" placeholder="https://…" dir="ltr"><button class="button" data-upload="${path}">رفع صورة</button></div>${get(path)?`<img class="thumb" src="${esc(get(path).startsWith('/assets/')?'/preview'+get(path):get(path))}" alt="معاينة">`:''}</div>`}
function render(){
 $('#panel-title').textContent=names[panel];document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===panel));
 let html='';
 if(panel==='overview')html=`<div class="grid"><div class="card stat"><p>لغات الموقع</p><strong>${data.brand.locales.length}</strong><span>العربية، الإنجليزية، الفرنسية والبرتغالية</span></div><div class="card stat"><p>مشاهد مفعلة</p><strong>${data.brand.motion.stories ? 1 + ['beauty','flight'].filter(type=>data.brand.motion.scenes.some(s=>s.enabled&&s.type===type)).length : 0}</strong><span>القلم + عارضة الأزياء + الطائرة</span></div></div><div class="card"><h2>من الفكرة إلى العرض</h2><p>غيّر حركة الكرة والمدارات، مدة المشاهد، صور المواقع، بيانات الشركة والنصوص بأربع لغات. أضف شعارات الشركاء وارفع الصور من جهازك.</p><p class="help">الحفظ يعيد بناء المعاينة ولا يغيّر الموقع العام. زر النشر يرفع النسخة المحفوظة إلى GitHub. احتفظ بهذه اللوحة على جهازك؛ لا تحتوي النسخة العامة على أدوات الإدارة.</p><div class="actions"><a class="button" href="/preview/ar/" target="_blank" rel="noopener">المعاينة العربية ↗</a><a class="button" href="/preview/en/" target="_blank" rel="noopener">المعاينة الإنجليزية ↗</a><button class="button" id="export">تنزيل نسخة المحتوى</button></div></div>`;
 if(panel==='brand')html=`<div class="card"><h2>هوية الشركة</h2><div class="grid">${field('اسم الشركة','brand.name')}${field('الاسم المختصر','brand.shortName')}${field('اللون الأساسي','brand.accent','color')}${field('لون الموشن','brand.accentBright','color')}${field('لون الخلفية','brand.surface','color')}${field('لون النصوص','brand.ink','color')}${field('البريد','brand.email','email')}${field('واتساب — أرقام دولية فقط','brand.whatsapp')}${field('رابط حجز مكالمة','brand.bookingUrl','url')}${field('رابط الموقع','brand.siteUrl','url')}${field('اللغة الافتراضية','brand.defaultLocale','select',[['ar','العربية'],['en','English'],['fr','Français'],['pt','Português']])}</div></div>`;
 if(panel==='motion')html=`<div class="card"><h2>الإيقاع والحركة</h2><div class="grid"><div>${field('تفعيل الموشن افتراضيًا','brand.motion.enabled','checkbox')}${field('دوران الكرة الأرضية','brand.motion.globe','checkbox')}${field('حركة المدارات','brand.motion.orbits','checkbox')}${field('عرض مشاهد المشاريع','brand.motion.stories','checkbox')}</div><div>${field('مدة تكرار الدورة بالثواني — من 6 إلى 30','brand.motion.duration','number')}${field('سرعة الكرة — من 0.1 إلى 3','brand.motion.globeSpeed','number')}<p class="help">يُحترم إعداد تقليل الحركة الخاص بالزائر. يمكنه أيضًا إيقاف الحركة من الموقع.</p></div></div></div><div class="card"><h2>مشاهد الأعمال</h2><button id="add-scene" class="button">+ إضافة مشهد</button><p class="help">التصميم يعرض ثلاثة كروت: AFRICA TECH، وأول مشهد أزياء مفعّل، وأول مشهد طائرة مفعّل. غيّر ترتيب المشاهد لاختيار المعروض. الأنواع الأخرى محفوظة ولا تظهر في هذا التصميم. ارفع صورة الموقع لاستبدال التكوين الافتراضي.</p>${data.brand.motion.scenes.map((s,i)=>`<div class="scene-row"><div class="scene-heading"><h3 dir="ltr">${esc(s.name)}</h3><div class="actions"><button class="button" data-move="${i}" data-direction="-1" ${i===0?'disabled':''}>↑</button><button class="button" data-move="${i}" data-direction="1" ${i===data.brand.motion.scenes.length-1?'disabled':''}>↓</button></div></div>${field('اسم العميل',`brand.motion.scenes.${i}.name`)}${field('نوع المشهد',`brand.motion.scenes.${i}.type`,'select',[['beauty','عارضة تكشف الموقع'],['flight','طائرة تسحب الموقع'],['dining','الترابيزة تتحول إلى موقع'],['studio','كاميرا وموقع']])}${field('إظهار المشهد',`brand.motion.scenes.${i}.enabled`,'checkbox')}${imageField('صورة المشروع',`brand.motion.scenes.${i}.image`)}</div>`).join('')}</div>`;
 if(panel==='partners')html=`<div class="card"><h2>شركاؤنا</h2><p class="help">يظهر القسم عندما يوجد شعار مرفوع ومفعّل. أسماء العملاء في قسم الأعمال منفصلة عن الشركاء.</p><button class="button primary" id="add-partner">+ إضافة شريك</button>${data.brand.motion.partners.length?data.brand.motion.partners.map((p,i)=>`<div class="scene-row"><div>${field('اسم الشريك',`brand.motion.partners.${i}.name`)}${field('إظهار الشعار',`brand.motion.partners.${i}.enabled`,'checkbox')}</div><div>${imageField('الشعار',`brand.motion.partners.${i}.logo`)}<button class="remove" data-remove-partner="${i}">حذف من القائمة</button></div></div>`).join(''):'<div class="empty">لم تُضف شعارات شركاء بعد.</div>'}</div>`;
 if(panel==='copy')html=`<div class="card"><h2>نصوص الموقع</h2><p class="help">تُطبّق التعديلات على الصفحات التي تستخدم هذا المحتوى. لا تحتاج إلى تعديل الكود.</p><div class="copy-toolbar"><select id="copy-language"><option value="ar">العربية</option><option value="en">English</option><option value="fr">Français</option><option value="pt">Português</option></select><select id="copy-group"><option value="ui">الواجهات والعناوين والتواصل</option><option value="expansion">المنصات والأعمال والقطاعات</option><option value="services">تفاصيل الخدمات</option><option value="sectors">تفاصيل القطاعات</option><option value="motionCopy">نصوص الموشن</option></select><input id="copy-search" placeholder="ابحث عن النص أو اسم الحقل"></div><div id="copy-list" class="copy-list"></div></div>`;
 $('#panel').innerHTML=html;bindFields();
 if(panel==='copy'){['#copy-language','#copy-group'].forEach(k=>$(k).addEventListener('change',renderCopy));$('#copy-search').addEventListener('input',renderCopy);renderCopy();}
 $('#export')?.addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='africa-tech-content.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)});
 $('#add-scene')?.addEventListener('click',()=>{data.brand.motion.scenes.push({id:'scene-'+Date.now(),name:'New project',type:'beauty',enabled:true,color:'#47604b',url:'',image:'',title:{ar:'مشروع جديد',en:'A new project',fr:'Un nouveau projet',pt:'Um novo projeto'}});setDirty();render()});
 $('#add-partner')?.addEventListener('click',()=>{data.brand.motion.partners.push({name:'',logo:'',enabled:true});setDirty();render()});
 document.querySelectorAll('[data-remove-partner]').forEach(b=>b.addEventListener('click',()=>{data.brand.motion.partners.splice(Number(b.dataset.removePartner),1);setDirty();render()}));
 document.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.move),j=i+Number(b.dataset.direction);if(j<0||j>=data.brand.motion.scenes.length)return;[data.brand.motion.scenes[i],data.brand.motion.scenes[j]]=[data.brand.motion.scenes[j],data.brand.motion.scenes[i]];setDirty();render()}));
}
function bindFields(root=document){root.querySelectorAll('[data-path]').forEach(input=>input.addEventListener('input',()=>put(input.dataset.path,input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value)));root.querySelectorAll('[data-upload]').forEach(b=>b.addEventListener('click',()=>{uploadTarget=b.dataset.upload;$('#image-file').click()}));}
function renderCopy(){const l=$('#copy-language').value,g=$('#copy-group').value,q=$('#copy-search').value.toLowerCase(),entries=[];function walk(o,p){if(typeof o==='string')entries.push([p,o]);else if(o&&typeof o==='object')Object.entries(o).forEach(([k,v])=>walk(v,p+'.'+k));}
 if(['ui','expansion','motionCopy'].includes(g))walk(data[g][l],g+'.'+l);else data[g].forEach((item,i)=>walk(item[l],g+'.'+i+'.'+l));
 $('#copy-list').innerHTML=entries.filter(([k,v])=>!q||k.toLowerCase().includes(q)||v.toLowerCase().includes(q)).map(([path,v])=>`<label class="form-field"><span class="key-label">${path}</span><textarea dir="${l==='ar'?'rtl':'ltr'}" data-path="${path}">${esc(v)}</textarea></label>`).join('');bindFields($('#copy-list'));}
$('#image-file').addEventListener('change',async()=>{const file=$('#image-file').files[0];if(!file)return;if(file.size>6*1024*1024){status('الحد الأقصى للصورة 6 ميجابايت',true);return}try{const bytes=new Uint8Array(await file.arrayBuffer());let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));const result=await api('upload',{type:file.type,data:btoa(raw)});put(uploadTarget,result.url);render();status('تم رفع الصورة. احفظ المحتوى لاستخدامها.')}catch(e){status(e.message,true)}$('#image-file').value=''});
async function save(publish=false){$('#save').disabled=$('#publish').disabled=true;status(publish?'جارٍ الحفظ والتحقق والنشر…':'جارٍ الحفظ وبناء المعاينة…');try{const r=await api(publish?'publish':'save',data);dirty=false;$('#dirty-label').textContent='كل التعديلات محفوظة';status(r.message)}catch(e){status(e.message,true)}finally{$('#save').disabled=$('#publish').disabled=false}}
$('#save').addEventListener('click',()=>save());$('#publish').addEventListener('click',()=>$('#publish-dialog').showModal());$('#cancel-publish').addEventListener('click',()=>$('#publish-dialog').close());$('#confirm-publish').addEventListener('click',()=>{$('#publish-dialog').close();save(true)});document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',()=>{panel=b.dataset.panel;render()}));window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
api('content').then(r=>{data=r.content;for(const s of data.brand.motion.scenes)s.title||={ar:'',en:'',fr:'',pt:''};token=r.token;render()}).catch(e=>status(e.message,true));
})();
