export const ui = {
 en: {
  nav:['Services','Solutions','Our approach'], start:'Start a project',skip:'Skip to content',menu:'Open navigation',close:'Close', language:'العربية',
  eyebrow:'AFRICAN ROOTS. GLOBAL AMBITION.',hero:['Big ideas.','Built beyond','boundaries.'],heroDesc:'From the first spark to your next big leap. We design, build and power the digital experiences that move your business forward.',explore:'Explore our capabilities',heroNote:'STRATEGY → DESIGN → ENGINEERING → GROWTH',scroll:'Scroll to discover',
  strip:['Digital experiences','Intelligent systems','Cloud infrastructure','One connected partner'],
  serviceEyebrow:'01 / WHAT WE DO',serviceTitle:'Every ambition.\nThe right technology.',serviceDesc:'A complete technology partner, from the experience your customers see to the systems that make it all work.',allServices:'Discover all services',learn:'Explore service',
  selectedEyebrow:'02 / POSSIBILITIES, MADE TANGIBLE',selectedTitle:'Ideas you can\ninteract with.',selectedDesc:'Explore two interface concepts. A glimpse of how thoughtful design turns complex operations into simple experiences.',concept:'INTERACTIVE CONCEPT',viewDemo:'Explore the concept',clinicTitle:'A clearer picture of care.',clinicDesc:'Appointments, patient journeys and daily operations. Connected in one calm workspace.',fleetTitle:'Keep every move connected.',fleetDesc:'A single view of your fleet, routes and deliveries. Built around the people making it happen.',
  globalEyebrow:'03 / BUILT FOR YOUR WORLD',globalTitle:'Rooted in Africa.\nOpen to the world.',globalDesc:'Great technology understands the place it serves. We shape digital products around real people, local contexts and ambitions that cross borders.',globalItems:[['Local context','Language, connectivity and the way your customers pay, considered from the beginning.'],['Global thinking','Clear architecture and thoughtful interfaces, ready for your next stage of growth.'],['Long-term partnership','From the first conversation to launch, maintenance and what comes next.']],
  processEyebrow:'04 / HOW WE GET THERE',processTitle:'Clarity at every step.',processDesc:'You bring the ambition. Together, we make a practical path from idea to impact.',steps:[['Discover','Understand your business, your users and what success should look like.'],['Design','Make the experience tangible with prototypes, clear flows and a shared direction.'],['Build','Engineer in focused stages, with regular reviews and visible progress.'],['Evolve','Launch thoughtfully, learn from real use and keep improving.']],
  ctaEyebrow:'YOUR NEXT CHAPTER STARTS HERE',ctaTitle:'Let’s build\nsomething that matters.',ctaDesc:'A new idea. A complex challenge. A better way forward.',footerDesc:'Technology with purpose.\nPossibilities without borders.',footerLabels:['Explore','Expertise','Let’s connect'],footerNote:'An African perspective. A global ambition.',privacy:'Privacy',backTop:'Back to top',
  servicesTitle:'Technology,\nworking together.',servicesIntro:'A beautiful website is just the beginning. Connect your digital presence, your operations and your infrastructure with one considered approach.',included:'What we can build',delivery:'How we work together',deliveryText:'We agree on scope, priorities and delivery milestones before development begins. Every project includes a documented handover and a clear support plan.',related:'Explore more capabilities',
  solutionsTitle:'Your industry.\nA new perspective.',solutionsIntro:'The best solutions start with understanding your work. Explore practical ways technology can simplify the everyday and open up what is possible.',all:'All industries',industry:'INDUSTRY SOLUTIONS',industryCta:'Discuss your requirements',sectorLabel:'Explore the opportunity',
  studioTitle:'Curious minds.\nConsidered technology.',studioIntro:'AFRICA TECH is a vision for a connected technology partner: bringing strategy, design and engineering into the same conversation.',beliefTitle:'Good work starts\nwith better questions.',beliefDesc:'What are we solving? Who are we building for? What happens after launch? We bring these questions into every stage, keeping the work grounded in your business.',values:[['Purpose before features','Choose the things that make a difference to your customers and your team.'],['Craft in the details','From the first interaction to the final handover, the details shape the experience.'],['Open collaboration','Clear decisions, shared priorities and a process you can see.'],['Built to grow','Practical foundations that can evolve alongside your organisation.']],
  contactTitle:'Big things begin\nwith a conversation.',contactIntro:'Tell us a little about what you have in mind. We’ll help turn the moving pieces into a clear project brief.',formLabels:['Your name','Work email','Company','What would you like to build?','Tell us about your idea'],formPlaceholders:['How should we call you?','you@company.com','Company or organisation','The challenge, the idea, the possibilities…'],select:'Select a service',budget:'Project stage',budgetOptions:['Exploring an idea','Ready to get started','Improving an existing product'],formAction:'Prepare my project brief',formNote:'Your information stays in this browser. Preparing a brief does not send an enquiry.',formReady:'Your project brief is ready.',formReadyDesc:'Review and download it below. No enquiry has been sent.',download:'Download project brief',emailBrief:'Open email with this brief',reset:'Edit my brief',optional:'Optional',privacyText:'Only share information you are comfortable including in a project brief.',contactAside:'A useful first conversation',contactList:['Your goals and what matters most','The people who will use it','The right starting point','Scope, timing and next steps'],
  faqTitle:'A few things you might be wondering.',faqs:[['Can we start with a small project?','Yes. A focused website, prototype or integration is often the right place to start. The scope can grow as the direction becomes clearer.'],['Can you work with our existing systems?','We begin by reviewing your current setup, access and integration options, then recommend a practical path forward.'],['Who owns the code and design?','Ownership, licences and handover are agreed in the project scope before work begins, so responsibilities are clear from the start.'],['What happens after launch?','We can define an ongoing support plan covering maintenance, hosting and future improvements according to your needs.']],
  demoNotice:'Illustrative interface with sample data. This is a design concept, not a live client system.',demoTab:['Overview','Appointments'],demoFilter:['All deliveries','In transit','Delivered'],demoClose:'Close concept',demoBook:'Discuss a similar project',
  privacyTitle:'Your privacy,\nby design.',privacyIntro:'How this demonstration website handles information.',privacyBody:[['Project briefs','The project form runs in your browser. Preparing or downloading a brief does not send your information to us. If you choose an email or WhatsApp action, that service handles the message.'],['Browser preferences','The site does not use analytics or advertising cookies. Navigation and interface settings are limited to the current page.'],['Hosting','The hosting provider may process technical request information to deliver the website. Its own privacy terms apply.'],['Before a public launch','This demonstration notice must be updated with the final company identity, contact information and the actual services used to receive enquiries.']],
  notFound:'This page has moved beyond the map.',home:'Back to home',techLabel:'BUILT AROUND YOUR BUSINESS',serviceAside:'One idea. Many possibilities.',demoNames:['Clinic workspace','Fleet command'],navSolutions:'Industry solutions'
 },
 ar:{
  nav:['خدماتنا','حلول القطاعات','منهجنا'],start:'ابدأ مشروعك',skip:'انتقل إلى المحتوى',menu:'افتح القائمة',close:'إغلاق',language:'English',
  eyebrow:'جذور أفريقية. طموح عالمي.',hero:['أفكار كبيرة.','نبنيها بلا','حدود.'],heroDesc:'من الشرارة الأولى إلى خطوتك الكبيرة القادمة. نصمم ونطور ونشغّل تجارب رقمية تدفع أعمالك للأمام.',explore:'اكتشف قدراتنا',heroNote:'استراتيجية ← تصميم ← تطوير ← نمو',scroll:'اكتشف المزيد',
  strip:['تجارب رقمية','أنظمة ذكية','بنية سحابية','شريك تقني متكامل'],
  serviceEyebrow:'01 / ماذا نقدم',serviceTitle:'لكل طموح.\nالتقنية المناسبة.',serviceDesc:'شريك تقني متكامل، من التجربة التي يراها عملاؤك إلى الأنظمة التي تدير أعمالك من الداخل.',allServices:'اكتشف كل الخدمات',learn:'اكتشف الخدمة',
  selectedEyebrow:'02 / أفكار تصبح ملموسة',selectedTitle:'أفكار يمكنك\nالتفاعل معها.',selectedDesc:'استكشف نموذجين لواجهات تفاعلية يوضّحان كيف يحوّل التصميم المدروس العمليات المعقدة إلى تجارب بسيطة.',concept:'تصور تفاعلي',viewDemo:'استكشف التصور',clinicTitle:'رؤية أوضح للرعاية.',clinicDesc:'المواعيد ورحلة المريض والعمليات اليومية، في مساحة عمل واحدة منظّمة.',fleetTitle:'كل حركة، على اتصال.',fleetDesc:'صورة واحدة للأسطول والمسارات والتوصيل، مصممة حول الأشخاص الذين يديرون العمل.',
  globalEyebrow:'03 / نفهم عالمك',globalTitle:'من أفريقيا.\nإلى آفاق العالم.',globalDesc:'التقنية الجيدة تفهم البيئة التي تعمل فيها. نبني المنتجات الرقمية حول الناس واحتياجاتهم المحلية وطموحاتهم التي تتجاوز الحدود.',globalItems:[['نفهم السياق المحلي','اللغة والاتصال وطرق الدفع التي يستخدمها عملاؤك، جزء من التفكير منذ البداية.'],['نفكر عالميًا','بنية واضحة وتجارب استخدام مدروسة تستوعب الخطوة التالية لنمو أعمالك.'],['شراكة مستمرة','من الحوار الأول إلى الإطلاق والصيانة، ثم ما يأتي بعد ذلك.']],
  processEyebrow:'04 / كيف نصل للنتيجة',processTitle:'وضوح في كل خطوة.',processDesc:'أنت تأتي بالطموح. ومعًا نرسم طريقًا عمليًا من الفكرة إلى الأثر.',steps:[['نكتشف','نفهم عملك ومستخدميك وما تعنيه النتيجة الناجحة بالنسبة لك.'],['نصمم','نحوّل التجربة إلى نماذج ملموسة ومسارات واضحة واتجاه مشترك.'],['نبني','نطور على مراحل محددة، مع مراجعات منتظمة وتقدم يمكنك متابعته.'],['نطوّر باستمرار','نطلق بعناية، ونتعلم من الاستخدام الفعلي، ونواصل التحسين.']],
  ctaEyebrow:'فصلك القادم يبدأ هنا',ctaTitle:'لنبنِ معًا\nشيئًا يصنع فرقًا.',ctaDesc:'فكرة جديدة. تحدٍ معقد. طريق أفضل للأمام.',footerDesc:'تقنية لها هدف.\nوإمكانيات بلا حدود.',footerLabels:['استكشف','خبراتنا','لنبقَ على اتصال'],footerNote:'رؤية أفريقية. طموح عالمي.',privacy:'الخصوصية',backTop:'العودة للأعلى',
  servicesTitle:'تقنية متكاملة.\nتعمل من أجلك.',servicesIntro:'الموقع المميز هو البداية. اربط حضورك الرقمي وعملياتك وبنيتك التقنية برؤية واحدة متكاملة.',included:'ما يمكننا بناؤه',delivery:'كيف نعمل معًا',deliveryText:'نتفق على النطاق والأولويات ومراحل التسليم قبل بدء التطوير. ويشمل كل مشروع تسليمًا موثقًا وخطة دعم واضحة.',related:'اكتشف المزيد من قدراتنا',
  solutionsTitle:'قطاعك.\nبرؤية جديدة.',solutionsIntro:'تبدأ الحلول المناسبة بفهم طبيعة عملك. استكشف كيف تبسّط التقنية التفاصيل اليومية وتفتح فرصًا جديدة.',all:'كل القطاعات',industry:'حلول القطاعات',industryCta:'ناقش متطلباتك',sectorLabel:'اكتشف الفرصة',
  studioTitle:'عقول فضولية.\nوتقنية مدروسة.',studioIntro:'AFRICA TECH رؤية لشريك تقني متكامل، يجمع الاستراتيجية والتصميم والتطوير في حوار واحد.',beliefTitle:'العمل الجيد يبدأ\nبأسئلة أفضل.',beliefDesc:'ماذا نحل؟ ولمن نبني؟ وماذا بعد الإطلاق؟ نطرح هذه الأسئلة في كل مرحلة لتبقى التقنية مرتبطة باحتياجات عملك.',values:[['الهدف قبل المزايا','نختار ما يصنع فرقًا حقيقيًا لعملائك وفريقك.'],['العناية بالتفاصيل','من أول تفاعل إلى التسليم النهائي، التفاصيل تصنع التجربة.'],['تعاون واضح','قرارات مفهومة وأولويات مشتركة وخطوات يمكنك متابعتها.'],['قابلية للنمو','أسس عملية تتطور مع تطور مؤسستك.']],
  contactTitle:'الأفكار الكبيرة\nتبدأ بحوار.',contactIntro:'احكِ لنا قليلًا عما تفكر فيه. سنساعدك على ترتيب التفاصيل في موجز واضح لمشروعك.',formLabels:['اسمك','البريد الإلكتروني للعمل','الشركة','ماذا تريد أن تبني؟','احكِ لنا عن فكرتك'],formPlaceholders:['بأي اسم نناديك؟','you@company.com','اسم الشركة أو المؤسسة','التحدي أو الفكرة أو الإمكانيات التي تتخيلها…'],select:'اختر الخدمة',budget:'مرحلة المشروع',budgetOptions:['أستكشف فكرة','جاهز للبدء','أطور منتجًا قائمًا'],formAction:'جهّز موجز مشروعي',formNote:'تظل بياناتك داخل هذا المتصفح. تجهيز الموجز لا يرسل طلبًا للشركة.',formReady:'موجز مشروعك جاهز.',formReadyDesc:'راجعه وحمّله من هنا. لم يتم إرسال أي طلب.',download:'تحميل موجز المشروع',emailBrief:'افتح البريد بهذا الموجز',reset:'عدّل الموجز',optional:'اختياري',privacyText:'اكتب فقط المعلومات التي ترغب في مشاركتها ضمن موجز المشروع.',contactAside:'حوار أول يستحق وقتك',contactList:['أهدافك وأهم أولوياتك','من سيستخدم المنتج','نقطة البداية المناسبة','النطاق والتوقيت والخطوات التالية'],
  faqTitle:'أسئلة قد تدور في بالك.',faqs:[['هل يمكن أن نبدأ بمشروع صغير؟','بالتأكيد. موقع محدد النطاق أو نموذج أولي أو ربط بين نظامين قد يكون البداية الأنسب. ويمكن توسيع النطاق عندما تتضح الرؤية.'],['هل يمكن العمل مع أنظمتنا الحالية؟','نبدأ بمراجعة الأنظمة الحالية والصلاحيات وخيارات الربط المتاحة، ثم نقترح مسارًا عمليًا للتنفيذ.'],['من يملك الكود والتصميم؟','نتفق على الملكية والتراخيص وآلية التسليم في نطاق المشروع قبل بدء العمل، لتكون المسؤوليات واضحة منذ البداية.'],['ماذا يحدث بعد الإطلاق؟','يمكن الاتفاق على خطة مستمرة للصيانة والاستضافة والتحسينات المستقبلية وفق احتياجاتك.']],
  demoNotice:'واجهة توضيحية ببيانات تجريبية. هذا تصور تصميمي وليس نظامًا فعليًا لعميل.',demoTab:['نظرة عامة','المواعيد'],demoFilter:['كل الشحنات','في الطريق','تم التسليم'],demoClose:'إغلاق التصور',demoBook:'ناقش مشروعًا مشابهًا',
  privacyTitle:'خصوصيتك.\nضمن التصميم.',privacyIntro:'كيف تتعامل هذه النسخة التجريبية مع المعلومات.',privacyBody:[['موجز المشروع','يعمل النموذج داخل المتصفح. تجهيز الموجز أو تحميله لا يرسل بياناتك إلينا. عند اختيار البريد أو واتساب، تتولى الخدمة المختارة التعامل مع الرسالة.'],['تفضيلات المتصفح','لا يستخدم الموقع أدوات تحليلات أو ملفات تعريف ارتباط إعلانية. تقتصر إعدادات الواجهة على الصفحة الحالية.'],['الاستضافة','قد يعالج مزود الاستضافة معلومات تقنية عن الطلبات لتشغيل الموقع. وتُطبق سياسة الخصوصية الخاصة به.'],['قبل الإطلاق العام','يجب تحديث هذا الإشعار التجريبي ببيانات الشركة النهائية ووسائل التواصل والخدمات الفعلية المستخدمة لاستقبال الطلبات.']],
  notFound:'هذه الصفحة خارج الخريطة.',home:'العودة للرئيسية',techLabel:'نصمم حول احتياجات عملك',serviceAside:'فكرة واحدة. احتمالات كثيرة.',demoNames:['مساحة العيادة','إدارة الأسطول'],navSolutions:'حلول القطاعات'
 }
};
export const services=[
 {slug:'websites',icon:'web',en:{name:'Websites & digital experiences',short:'Web & experiences',desc:'First impressions that open new possibilities. Fast, expressive websites and commerce experiences built around your brand.',items:['Company and brand websites','E-commerce and customer portals','Multilingual experiences','Content systems and search visibility'],tag:'YOUR DIGITAL FRONT DOOR'},ar:{name:'المواقع والتجارب الرقمية',short:'المواقع والتجارب',desc:'انطباع أول يفتح فرصًا جديدة. مواقع ومتاجر سريعة ومعبرة، مصممة حول هوية شركتك.',items:['مواقع الشركات والعلامات التجارية','المتاجر وبوابات العملاء','تجارب متعددة اللغات','إدارة المحتوى والظهور في البحث'],tag:'بوابتك إلى العالم الرقمي'}},
 {slug:'mobile-apps',icon:'mobile',en:{name:'Mobile applications',short:'Mobile applications',desc:'Useful, intuitive experiences that stay close to your customers. From the first tap to the moments that matter.',items:['iOS and Android applications','User experience and prototyping','Notifications and device integrations','Store launch and release planning'],tag:'IN YOUR CUSTOMERS’ HANDS'},ar:{name:'تطبيقات الموبايل',short:'تطبيقات الموبايل',desc:'تجارب سهلة ومفيدة تبقى قريبة من عملائك، من اللمسة الأولى إلى اللحظات المهمة.',items:['تطبيقات iOS وAndroid','تجربة المستخدم والنماذج الأولية','الإشعارات وربط إمكانيات الجهاز','التجهيز للنشر وإدارة الإصدارات'],tag:'أقرب إلى عملائك'}},
 {slug:'business-systems',icon:'system',en:{name:'Business systems & platforms',short:'Business systems',desc:'Less friction. More clarity. Purpose-built software that connects your people, data and everyday operations.',items:['ERP and CRM solutions','Internal dashboards and workflows','Inventory and operational systems','Integrations and data migration'],tag:'BRING YOUR BUSINESS TOGETHER'},ar:{name:'أنظمة ومنصات الأعمال',short:'أنظمة الأعمال',desc:'تعقيد أقل ووضوح أكبر. برمجيات مخصصة تربط فريقك وبياناتك وعملياتك اليومية.',items:['حلول إدارة الموارد والعملاء','لوحات التحكم ومسارات العمل','أنظمة المخزون والتشغيل','الربط بين الأنظمة ونقل البيانات'],tag:'أعمالك في صورة واحدة'}},
 {slug:'cloud-hosting',icon:'cloud',en:{name:'Cloud & hosting',short:'Cloud & hosting',desc:'A strong foundation for everything you build. Hosting and infrastructure shaped around your performance and growth needs.',items:['Website and application hosting','Cloud architecture and deployment','Backup and recovery planning','Performance monitoring and optimisation'],tag:'A FOUNDATION FOR WHAT’S NEXT'},ar:{name:'السحابة والاستضافة',short:'السحابة والاستضافة',desc:'أساس قوي لكل ما تبنيه. استضافة وبنية تقنية تتناسب مع احتياجات الأداء والنمو.',items:['استضافة المواقع والتطبيقات','تصميم البنية السحابية والنشر','خطط النسخ الاحتياطي والاستعادة','مراقبة الأداء وتحسينه'],tag:'أساس لخطوتك القادمة'}},
 {slug:'ai-automation',icon:'spark',en:{name:'AI & intelligent automation',short:'AI & automation',desc:'Make more room for meaningful work. Connect your tools, streamline repetitive tasks and explore practical uses of AI.',items:['Workflow and process automation','Knowledge assistants and search','Document and data processing','AI integration and human review flows'],tag:'MORE POSSIBILITY. LESS REPETITION.'},ar:{name:'الذكاء الاصطناعي والأتمتة',short:'الذكاء الاصطناعي والأتمتة',desc:'وقت أكبر للعمل المهم. نربط أدواتك ونبسط المهام المتكررة ونستكشف تطبيقات عملية للذكاء الاصطناعي.',items:['أتمتة العمليات ومسارات العمل','مساعدو المعرفة والبحث','معالجة المستندات والبيانات','دمج الذكاء الاصطناعي والمراجعة البشرية'],tag:'فرص أكثر. تكرار أقل.'}},
 {slug:'support',icon:'support',en:{name:'Technology support & evolution',short:'Support & evolution',desc:'Launch is a beginning. Keep your technology healthy, your team supported and your next improvements moving.',items:['Maintenance and updates','Technical troubleshooting','Roadmaps and product improvements','Documented handover and team training'],tag:'WITH YOU BEYOND LAUNCH'},ar:{name:'الدعم والتطوير المستمر',short:'الدعم والتطوير',desc:'الإطلاق بداية. نحافظ على كفاءة تقنياتك وندعم فريقك ونتحرك معك نحو التحسين التالي.',items:['الصيانة والتحديثات','حل المشكلات التقنية','خطط التطوير وتحسين المنتجات','تسليم موثق وتدريب الفريق'],tag:'معك بعد الإطلاق'}}
];
export const sectors=[
 {slug:'healthcare',icon:'health',category:'people',en:{name:'Healthcare',title:'More time for care.\nLess time for paperwork.',desc:'Connect appointments, patient communication and clinic operations with software shaped around the way your team works.',items:['Appointment scheduling','Patient portals','Clinic operations','Reporting and integrations']},ar:{name:'الرعاية الصحية',title:'وقت أكبر للرعاية.\nوأقل للأوراق.',desc:'اربط المواعيد والتواصل مع المرضى وعمليات العيادة ببرمجيات تناسب طريقة عمل فريقك.',items:['تنظيم المواعيد','بوابات المرضى','عمليات العيادة','التقارير وربط الأنظمة']}},
 {slug:'logistics',icon:'truck',category:'business',en:{name:'Logistics & transport',title:'Every move.\nA clearer view.',desc:'Bring vehicles, deliveries and customer updates into a connected operational experience.',items:['Fleet dashboards','Delivery workflows','Customer tracking portals','Route and dispatch integrations']},ar:{name:'النقل واللوجستيات',title:'كل حركة.\nفي صورة أوضح.',desc:'اجمع المركبات والشحنات وتحديثات العملاء في تجربة تشغيلية مترابطة.',items:['لوحات إدارة الأسطول','عمليات التوصيل','بوابات تتبع للعملاء','ربط المسارات وإدارة الإرسال']}},
 {slug:'education',icon:'book',category:'people',en:{name:'Education',title:'Better connected.\nBetter learning.',desc:'Simplify the administration around learning, bringing students, families and educators closer.',items:['School management','Learning platforms','Parent communication','Admissions and payments']},ar:{name:'التعليم',title:'اتصال أفضل.\nوتعلم أفضل.',desc:'بسّط إدارة العملية التعليمية وقرّب الطلاب وأولياء الأمور والمعلمين.',items:['إدارة المدارس','منصات التعلم','التواصل مع أولياء الأمور','القبول والمدفوعات']}},
 {slug:'commerce',icon:'bag',category:'business',en:{name:'Retail & commerce',title:'From discovery\nto the next order.',desc:'Make shopping feel effortless, while keeping your catalogues, orders and inventory connected.',items:['Online storefronts','Inventory management','Payment integrations','Customer engagement']},ar:{name:'التجارة والتجزئة',title:'من الاكتشاف\nإلى الطلب التالي.',desc:'اجعل التسوق أسهل، مع ربط المنتجات والطلبات والمخزون في تجربة متكاملة.',items:['المتاجر الإلكترونية','إدارة المخزون','ربط طرق الدفع','التواصل مع العملاء']}},
 {slug:'hospitality',icon:'cup',category:'business',en:{name:'Hospitality',title:'A better experience.\nBefore they arrive.',desc:'Thoughtful digital touchpoints for restaurants, hotels and the people they welcome.',items:['Booking experiences','Digital menus','Ordering platforms','Guest communication']},ar:{name:'الضيافة والمطاعم',title:'تجربة أفضل.\nقبل الوصول.',desc:'نقاط تواصل رقمية مدروسة للمطاعم والفنادق وضيوفها.',items:['تجارب الحجز','القوائم الرقمية','منصات الطلب','التواصل مع الضيوف']}},
 {slug:'organisations',icon:'globe',category:'people',en:{name:'Organisations & impact',title:'Technology that\nserves your mission.',desc:'Tools that support field teams, connect programme information and make reporting clearer.',items:['Programme management','Field data collection','Volunteer coordination','Impact reporting']},ar:{name:'المؤسسات والعمل المجتمعي',title:'تقنية تدعم\nرسالتك.',desc:'أدوات تساعد فرق الميدان وتربط بيانات البرامج وتجعل التقارير أوضح.',items:['إدارة البرامج','جمع البيانات الميدانية','تنسيق المتطوعين','تقارير الأثر']}}
];
