export const motionCopy={
 en:{eyebrow:'FROM THE FIRST LINE TO THE FINAL EXPERIENCE',title:'Ideas, brought\nto life.',intro:'A pencil stroke becomes a digital experience. Discover the stories behind our work.',draw:'Sketch',build:'Create',reveal:'Reveal',replay:'Replay story',pause:'Pause motion',play:'Play motion',next:'Next story',previous:'Previous story',view:'Discuss a similar project',partners:'Our partners',partnerIntro:'The people and technologies we work with.',client:'Client',stories:['A beautiful experience, revealed.','A website ready for takeoff.','From the table to the screen.','A little appetite. A big idea.','Every frame tells a story.'],senior:'Senior Kofta is one of our restaurant clients.',storyLabel:'Project story',previewNote:'Creative project presentation'},
 ar:{eyebrow:'من أول خط إلى تجربة متكاملة',title:'أفكارنا.\nتدبّ فيها الحياة.',intro:'خط بالقلم يتحول لتجربة رقمية. اكتشف الحكاية وراء كل مشروع.',draw:'نرسم',build:'نبتكر',reveal:'نكشف',replay:'أعد المشهد',pause:'إيقاف الحركة',play:'تشغيل الحركة',next:'المشهد التالي',previous:'المشهد السابق',view:'ناقش مشروعًا مشابهًا',partners:'شركاؤنا',partnerIntro:'الجهات والتقنيات التي نتعاون معها.',client:'عميل',stories:['تجربة جميلة، تنكشف أمامك.','موقع يستعد للإقلاع.','من الترابيزة إلى الشاشة.','شهية مفتوحة. وفكرة كبيرة.','كل كادر يحكي حكاية.'],senior:'سنيور كفتة أحد عملائنا في قطاع المطاعم.',storyLabel:'حكاية مشروع',previewNote:'عرض إبداعي للمشروع'},
 fr:{eyebrow:'DU PREMIER TRAIT À L’EXPÉRIENCE',title:'Des idées\nqui prennent vie.',intro:'Un trait de crayon devient une expérience numérique. Découvrez nos projets en mouvement.',draw:'Dessiner',build:'Créer',reveal:'Révéler',replay:'Rejouer',pause:'Suspendre les animations',play:'Activer les animations',next:'Scène suivante',previous:'Scène précédente',view:'Parlons d’un projet similaire',partners:'Nos partenaires',partnerIntro:'Les équipes et technologies avec lesquelles nous collaborons.',client:'Client',stories:['Une belle expérience se dévoile.','Un site prêt à décoller.','De la table à l’écran.','Un bel appétit. Une grande idée.','Chaque image raconte une histoire.'],senior:'Senior Kofta compte parmi nos clients dans la restauration.',storyLabel:'Histoire du projet',previewNote:'Présentation créative du projet'},
 pt:{eyebrow:'DO PRIMEIRO TRAÇO À EXPERIÊNCIA',title:'Ideias\nque ganham vida.',intro:'Um traço de lápis transforma-se numa experiência digital. Conheça os nossos projetos em movimento.',draw:'Desenhar',build:'Criar',reveal:'Revelar',replay:'Repetir cena',pause:'Pausar animações',play:'Ativar animações',next:'Próxima cena',previous:'Cena anterior',view:'Falar de um projeto semelhante',partners:'Os nossos parceiros',partnerIntro:'As equipas e tecnologias com que colaboramos.',client:'Cliente',stories:['Uma bela experiência revelada.','Um site pronto para descolar.','Da mesa para o ecrã.','Bom apetite. Uma grande ideia.','Cada imagem conta uma história.'],senior:'Senior Kofta é um dos nossos clientes na restauração.',storyLabel:'História do projeto',previewNote:'Apresentação criativa do projeto'}
};
export const defaultMotion={enabled:true,globe:true,orbits:true,stories:true,duration:7,globeSpeed:1,partners:[],scenes:[
 {id:'queen',name:'Queen Secret',type:'beauty',enabled:true,color:'#9d6f78',url:'',image:'',descriptionIndex:0},
 {id:'west',name:'West Wings',type:'flight',enabled:true,color:'#294b5b',url:'https://westwingscargo.com/',image:'',descriptionIndex:1},
 {id:'wimbi',name:'Wimbi',type:'dining',enabled:true,color:'#997b37',url:'',image:'',descriptionIndex:2},
 {id:'kofta',name:'Senior Kofta',type:'dining',enabled:true,color:'#a74028',url:'',image:'',descriptionIndex:3},
 {id:'switx',name:'Switx Visions',type:'studio',enabled:true,color:'#47604b',url:'',image:'',descriptionIndex:4}
]};
